---
# tasks file for mtk-firmware-upgrade
    - name: Get Firmware
      routeros_command:
        commands: /system routerboard print
      register: output

    - name: Get Upgrade Firmware Line
      set_fact:
        upgrade: "{{ item | replace('upgrade-firmware: ', '') | trim }}"
      when: "'upgrade-firmware:' in item"
      loop: "{{ output.stdout_lines[0] }}"

    - name: Get Current Firmware Line
      set_fact:
        current: "{{ item | replace('current-firmware: ', '') | trim }}"
      when: "'current-firmware:' in item"
      loop: "{{ output.stdout_lines[0] }}"

#    - debug:
#        var: upgrade
#    - debug:
#        var: current

    - name: Create update script
      routeros_command:
        commands: /system script add dont-require-permissions=no name=firm-upgrade source="/system rou up; /system reboot"
      when: current is version_compare(upgrade, '<')

    - name: Add schedule to call upgrade
      routeros_command:
        commands: !!str /system scheduler add disabled=no name=firm-upgrade on-event=firm-upgrade
      when: current is version_compare(upgrade, '<')

    - name: Set scheduler time for 1 min in the future if it needs to upgrade
      routeros_command:
        commands: !!str /system scheduler set [find name=firm-upgrade] disabled=no start-date=[/system clock get date] start-time=(([:pick [/system clock get time] 0 3]) . ([:pick [/system clock get time] 3 5] + 1) . ([:pick [/system clock get time] 5 8]))
      when: current is version_compare(upgrade, '<')
#      when: current != upgrade